[package]
name = "conversejs"
version = "1.5.2"
authors = ["luigi311 <ubports@luigi311.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
qmetaobject = "0.2"
gettext-rs = "0.7"
cstr = "0.2"
cpp = "0.5"
actix-web = "3"
actix-files = "0.5"

[build-dependencies]
cpp_build = "0.5"
