[package]
name = "conversejs"
version = "1.5.3"
authors = ["luigi311 <ubports@luigi311.com>"]
edition = "2018"
build = "src/build.rs"

[dependencies]
qmetaobject = "0.2"
gettext-rs = "0.7"
cstr = "0.2"
cpp = "0.5"
actix-web = "4.3.0"
actix-files = "0.6.2"

[build-dependencies]
cpp_build = "0.5"
