name: Clickable Build

on:
  push:
    paths-ignore:
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - .gitignore
      - "*.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, armhf]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: Install clickable
        run: |
          python3 -m pip install clickable-ut
      
      - name: Build
        run: |
          clickable build --arch ${{ matrix.arch }}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: conversejs.luigi311_${{ env.ARTIFACT_VERSION }}_${{ matrix.arch }}
          path: build/*/app/*.click
          if-no-files-found: error
      
      - name: Publish
        env:
          API_KEY: ${{ secrets.API_KEY }}
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          clickable publish --apikey ${{ env.API_KEY }} --arch ${{ matrix.arch }}

      - name: Changelog
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}

      - name: Create release
        if: startsWith(github.event.ref, 'refs/tags/v')
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{steps.build_changelog.outputs.changelog}}
          draft: false
          prerelease: false
