name: Clickable Build

on:
  push:
    paths-ignore:
      - .gitignore
      - "*.md"
  pull_request:
    paths-ignore:
      - .gitignore
      - "*.md"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64, armhf]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: Install clickable
        run: |
          python3 -m pip install clickable-ut
      
      - name: Build
        run: |
          clickable build --arch ${{ matrix.arch }}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: conversejs.luigi311_${{ matrix.arch }}
          path: build/*/app/*.click
          if-no-files-found: error
      
      - name: Publish
        env:
          APIKEY: ${{ secrets.APIKEY }}
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: |
          clickable publish --apikey ${{ env.APIKEY }} --arch ${{ matrix.arch }}

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
